# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint | Test 

on:
  pull_request:
    branches: [ "main" ]

env:
  GO_VER: '1.22.4'

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4
    - 
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VER }}
        cache: false
    - 
      name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

  test:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    steps:
    - 
      uses: actions/checkout@v4
    - 
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VER }}
    - 
      name: Run test suite
      run: |
        go test $(go list ./...)
